module AllGem
  VERSION: String

  class CLI
    attr_reader stdout: IO
    attr_reader sderr: IO
    attr_reader sdin: IO

    def initialize: (stdout: IO, stderr: IO, stdin: IO) -> void

    def run: () -> Integer
  end
end
