module AllGem
  VERSION: String

  class CLI
    class Error < StandardError
      attr_reader status: Integer

      def initialize: (String message, ?Integer status) -> void
    end

    class Options
      attr_accessor remote: bool
      attr_accessor since: Gem::Version?
      attr_accessor level: :all | :major | :minor | :patch
    end

    attr_reader stdout: IO
    attr_reader stderr: IO
    attr_reader stdin: IO
    attr_reader opts: Options
    attr_reader op: OptionParser

    @op: OptionParser

    def initialize: (stdout: IO, stderr: IO, stdin: IO) -> void

    def run: (Array[String]) -> void

    private

    def set_optparse: () -> void

    def help: () -> String

    def gemspec_from_command: (String command) -> Gem::Specification

    def versions_of: (Gem::Specification, Options) -> Array[Gem::Version]

    def local_versions: (Gem::Specification) -> Array[Gem::Version]

    def remote_versions: (Gem::Specification) -> Array[Gem::Version]

    def install!: (Gem::Specification, Array[Gem::Version]) -> void

    def filter_by_level: (Array[Gem::Version], Options) -> Array[Gem::Version]

    def no_bundler: [T] () { () -> T } -> T
  end
end
