module Gem
  class Specification < BasicSpecification
    extend Enumerable[Specification]

    attr_reader name: String
    attr_reader version: Version

    def self.each: () -> Enumerator[Specification, Array[Specification]]
            | () { (Specification) -> void } -> Array[Specification]

    def executables: () -> Array[String]
  end

  class NameTuple
    attr_reader name: String
    attr_reader version: Version
  end

  class Source
  end

  class Version
    def segments: () -> Array[Integer]
  end

  class SpecFetcher
    def self.fetcher: () -> instance

    type specs_type = :complete | :released | :prerelease | :latest

    def detect: (specs_type) { (NameTuple) -> boolish } -> Array[[NameTuple, Source]]
  end
end
