class Gem::Specification < Gem::BasicSpecification
  extend Enumerable[Gem::Specification]

  attr_reader name: String
  attr_reader version: Gem::Version

  def self.each: () -> Enumerator[Gem::Specification, Array[Gem::Specification]]
          | () { (Gem::Specification) -> void } -> Array[Gem::Specification]

  def executables: () -> Array[String]
end
